vich_uploader:
    db_driver: orm

    mappings:
        newsImage:
            uri_prefix: /img/products
            upload_destination: '%kernel.project_dir%/public/img/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
